AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Flink POC - Full pipeline: IAM Role + Kinesis Stream + S3 Bucket + Managed Flink App
  Flink Version  : 1.18
  Region         : eu-west-1
  JARs in S3     : jars/flink-sql-connector-kinesis-4.0.0-1.16.jar
                   jars/flink-s3-fs-hadoop-1.18.1.jar

# ──────────────────────────────────────────────────────────────
# FIXES APPLIED:
# 1. PermissionsBoundary → core-AppRolePermissionsBoundary (was wrong name)
# 2. All Tags removed → caused UnauthorizedTaggingOperation error
# ──────────────────────────────────────────────────────────────

Resources:

  # ── IAM Role ─────────────────────────────────────────────────
  FlinkServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "svc-flink-poc-role"
      Policies:
        - PolicyName: "flink-poc-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: "*"
                Action:
                  - s3:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - kinesisanalytics:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - kinesis:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - logs:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - cloudwatch:*
                Effect: "Allow"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "kinesisanalytics.amazonaws.com"
      # FIXED: correct policy name from error message
      PermissionsBoundary:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:policy/core-AppRolePermissionsBoundary'

  # ── Kinesis Input Stream ──────────────────────────────────────
  # Tags removed — caused UnauthorizedTaggingOperation error
  FlinkInputKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: "flink-poc-input-stream"
      ShardCount: 1
      RetentionPeriodHours: 24

  # ── S3 Output Bucket ──────────────────────────────────────────
  # Tags removed — caused UnauthorizedTaggingOperation error
  FlinkOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "flink-poc-output-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30

  # ── CloudWatch Log Group ──────────────────────────────────────
  # All logger.info() / logger.warning() from main.py appear here
  FlinkLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: "/aws/kinesis-analytics/flink-poc-app"
      RetentionInDays: 7

  FlinkLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FlinkLogGroup
      LogStreamName: "flink-app-logs"

  # ── AWS Managed Flink Application ─────────────────────────────
  FlinkApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    DependsOn:
      - FlinkServiceRole
      - FlinkInputKinesisStream
      - FlinkOutputBucket
    Properties:
      ApplicationName: "flink-poc-app"
      RuntimeEnvironment: "FLINK-1_18"
      ServiceExecutionRole: !GetAtt FlinkServiceRole.Arn

      ApplicationConfiguration:

        # ── Parallelism & Checkpointing ────────────────────
        FlinkApplicationConfiguration:
          ParallelismConfiguration:
            ConfigurationType: CUSTOM
            Parallelism: 1
            ParallelismPerKPU: 1
            AutoScalingEnabled: false
          CheckpointConfiguration:
            ConfigurationType: CUSTOM
            CheckpointingEnabled: true
            CheckpointInterval: 60000
            MinPauseBetweenCheckpoints: 5000
          MonitoringConfiguration:
            ConfigurationType: CUSTOM
            MetricsLevel: APPLICATION
            LogLevel: INFO

        # ── Python ZIP file location in S3 ────────────────
        # S3 bucket : flink-poc-app-nishikesh
        # S3 key    : python/flink-python-app.zip
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: "arn:aws:s3:::flink-poc-app-nishikesh"
              FileKey: "python/flink-python-app.zip"
          CodeContentType: ZIPFILE

        # ── Runtime Properties ─────────────────────────────
        EnvironmentProperties:
          PropertyGroups:

            # JAR files loaded from S3 — both separated by semicolon
            - PropertyGroupId: "kinesis.analytics.flink.run.options"
              PropertyMap:
                python: "main.py"
                jarfile: "jars/flink-sql-connector-kinesis-4.0.0-1.16.jar;jars/flink-s3-fs-hadoop-1.18.1.jar"

            # App config — read by get_config() in main.py
            - PropertyGroupId: "ApplicationProperties"
              PropertyMap:
                input.stream.name:  "flink-poc-input-stream"
                output.bucket.name: !Sub "flink-poc-output-${AWS::AccountId}"
                output.prefix:      "processed-logs"
                aws.region:         "eu-west-1"
                stream.position:    "LATEST"

  # ── CloudWatch Logging ─────────────────────────────────────────
  FlinkAppCloudWatchLogging:
    Type: AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption
    DependsOn: FlinkApplication
    Properties:
      ApplicationName: !Ref FlinkApplication
      CloudWatchLoggingOption:
        LogStreamARN: !Sub >-
          arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesis-analytics/flink-poc-app:log-stream:flink-app-logs

# ──────────────────────────────────────────────────────────────
# Outputs
# ──────────────────────────────────────────────────────────────
Outputs:

  FlinkRoleArn:
    Value: !GetAtt FlinkServiceRole.Arn
    Description: ARN of the Flink service role

  InputStreamName:
    Value: !Ref FlinkInputKinesisStream
    Description: "Kinesis input stream: flink-poc-input-stream"

  OutputBucketName:
    Value: !Ref FlinkOutputBucket
    Description: "S3 output bucket: flink-poc-output-<account-id>"

  FlinkAppName:
    Value: !Ref FlinkApplication
    Description: "Managed Flink app: flink-poc-app"

  CloudWatchLogGroup:
    Value: "/aws/kinesis-analytics/flink-poc-app"
    Description: View Flink logs here in CloudWatch
