AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Flink POC - Kinesis Stream + Output S3 Bucket + Managed Flink App
  Uses existing bucket flink-poc-app-nishikesh for app code and JARs.
  No IAM resources.

Parameters:

  ApplicationName:
    Type: String
    Default: flink-poc
    Description: Name of the Flink application

  ExistingAppBucket:
    Type: String
    Default: flink-poc-app-nishikesh
    Description: >
      Your EXISTING S3 bucket where JARs and ZIP are already uploaded.
      This bucket is NOT created by this template — it must already exist.

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues: [ 1, 3, 5, 7, 14, 30, 60, 90 ]

  FlinkRoleArn:
    Type: String
    Description: >
      ARN of the IAM role created by yugur.yaml (flink-iam-stack2).
      Value: arn:aws:iam::739275465799:role/svc-bsp-msf-flink-role

Resources:

  # ── CloudWatch Log Group ──────────────────────────────────────
  FlinkLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/kinesis-analytics/${ApplicationName}'
      RetentionInDays: !Ref LogRetentionDays

  FlinkLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FlinkLogGroup
      LogStreamName: "flink-app-logs"

  # ── S3 Output Bucket ──────────────────────────────────────────
  # Flink writes processed records here (new bucket, created by this template)
  FlinkOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::AccountId}-flink-poc-output'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: 30

  # ── Kinesis Input Stream ──────────────────────────────────────
  FlinkInputKinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub '${ApplicationName}-input-stream'
      ShardCount: 1
      RetentionPeriodHours: 24

  # ── AWS Managed Flink Application ─────────────────────────────
  FlinkApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    DependsOn:
      - FlinkInputKinesisStream
      - FlinkOutputBucket
    Properties:
      ApplicationName: !Sub '${ApplicationName}-app'
      RuntimeEnvironment: "FLINK-1_18"
      ServiceExecutionRole: !Ref FlinkRoleArn

      ApplicationConfiguration:

        FlinkApplicationConfiguration:
          ParallelismConfiguration:
            ConfigurationType: CUSTOM
            Parallelism: 1
            ParallelismPerKPU: 1
            AutoScalingEnabled: false
          CheckpointConfiguration:
            ConfigurationType: CUSTOM
            CheckpointingEnabled: true
            CheckpointInterval: 60000
            MinPauseBetweenCheckpoints: 5000
          MonitoringConfiguration:
            ConfigurationType: CUSTOM
            MetricsLevel: APPLICATION
            LogLevel: INFO

        # Points to your EXISTING bucket flink-poc-app-nishikesh
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: !Sub 'arn:aws:s3:::${ExistingAppBucket}'
              FileKey: "python/flink-python-app.zip"
          CodeContentType: ZIPFILE

        EnvironmentProperties:
          PropertyGroups:

            - PropertyGroupId: "kinesis.analytics.flink.run.options"
              PropertyMap:
                python: "main.py"
                jarfile: "jars/flink-sql-connector-kinesis-4.0.0-1.16.jar;jars/flink-s3-fs-hadoop-1.18.1.jar"

            - PropertyGroupId: "ApplicationProperties"
              PropertyMap:
                input.stream.name:  !Sub '${ApplicationName}-input-stream'
                output.bucket.name: !Sub '${AWS::AccountId}-flink-poc-output'
                output.prefix:      "processed-logs"
                aws.region:         !Ref "AWS::Region"
                stream.position:    "LATEST"

  # ── CloudWatch Logging ─────────────────────────────────────────
  FlinkAppCloudWatchLogging:
    Type: AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption
    DependsOn: FlinkApplication
    Properties:
      ApplicationName: !Ref FlinkApplication
      CloudWatchLoggingOption:
        LogStreamARN: !Sub >-
          arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesis-analytics/${ApplicationName}:log-stream:flink-app-logs

Outputs:

  ExistingAppBucket:
    Description: Existing bucket used for app code and JARs
    Value: !Ref ExistingAppBucket

  OutputBucketName:
    Description: Flink writes processed records here
    Value: !Ref FlinkOutputBucket

  InputStreamName:
    Description: Send records here from the generator
    Value: !Ref FlinkInputKinesisStream

  FlinkAppName:
    Description: Managed Flink application name
    Value: !Ref FlinkApplication

  CloudWatchLogGroup:
    Description: View Flink logs here
    Value: !Ref FlinkLogGroup
