AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template for Flink POC IAM role

Resources:
  FlinkServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        'Fn::Sub': 'svc-flink-poc-role'
      Policies:
        - PolicyName:
            'Fn::Sub': 'flink-poc-policy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: "*"
                Action:
                  - kinesisanalytics:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - kinesis:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - logs:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - cloudwatch:*
                Effect: "Allow"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "kinesisanalytics.amazonaws.com"
      PermissionsBoundary:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:policy/core-ServiceRolePermissionsBoundary'

Outputs:
  FlinkRoleArn:
    Value: !GetAtt FlinkServiceRole.Arn
    Description: ARN of the Flink service role
```

---

## Key Differences from the Sample Your Lead Shared

| Field | Sample (Glue) | Your Flink Template |
|-------|---------------|---------------------|
| RoleName | `svc-real-time-hydration-poc-role` | `svc-flink-poc-role` |
| Principal Service | AWS account role | `kinesisanalytics.amazonaws.com` |
| Policies | S3, KMS for Glue | Kinesis, Logs, CloudWatch for Flink |
| PermissionsBoundary | Same | Same (required!) |

---

## Deploy Command
```
aws cloudformation deploy --template-file "C:\Users\B01653960\Downloads\flink-iam-role.yaml" --stack-name flink-iam-role-stack --capabilities CAPABILITY_NAMED_IAM --region eu-west-1 --role-arn arn:aws:iam::739275465799:role/core-CloudformationStackAdmin
```

---

## After Role is Created

Once this succeeds, get the role ARN:
```
aws cloudformation describe-stacks --stack-name flink-iam-role-stack --region eu-west-1 --query "Stacks[0].Outputs"
