AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Flink Application Test

Resources:
  FlinkApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      ApplicationName: flink-test-app
      RuntimeEnvironment: FLINK-1_18
      ServiceExecutionRole: !Sub arn:aws:iam::${AWS::AccountId}:role/core-CloudformationStackAdmin
      ApplicationConfiguration:
        FlinkApplicationConfiguration:
          ParallelismConfiguration:
            ConfigurationType: CUSTOM
            Parallelism: 1
            ParallelismPerKPU: 1
            AutoScalingEnabled: false
        ApplicationSnapshotConfiguration:
          SnapshotsEnabled: false

Outputs:
  ApplicationName:
    Value: !Ref FlinkApplication
```
