Create a new file flink-studio-notebook.yaml:
yamlAWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Flink Studio Notebook with IAM Role

Resources:
  FlinkStudioRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName:
        'Fn::Sub': 'svc-flink-studio-role'
      Policies:
        - PolicyName:
            'Fn::Sub': 'flink-studio-policy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Resource: "*"
                Action:
                  - kinesisanalytics:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - kinesis:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - logs:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - cloudwatch:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - glue:*
                Effect: "Allow"
              - Resource: "*"
                Action:
                  - s3:*
                Effect: "Allow"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service: "kinesisanalytics.amazonaws.com"
      PermissionsBoundary:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:policy/core-ServiceRolePermissionsBoundary'

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: flink_poc_database
        Description: Database for Flink POC

  FlinkStudioNotebook:
    Type: AWS::KinesisAnalyticsV2::Application
    DependsOn:
      - FlinkStudioRole
      - GlueDatabase
    Properties:
      ApplicationName: flink-poc-notebook
      ApplicationMode: INTERACTIVE
      RuntimeEnvironment: ZEPPELIN-FLINK-3_0
      ServiceExecutionRole: !GetAtt FlinkStudioRole.Arn
      ApplicationConfiguration:
        FlinkApplicationConfiguration:
          ParallelismConfiguration:
            ConfigurationType: CUSTOM
            Parallelism: 4
            ParallelismPerKPU: 1
            AutoScalingEnabled: false
        ZeppelinApplicationConfiguration:
          CatalogConfiguration:
            GlueDataCatalogConfiguration:
              DatabaseARN: !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/flink_poc_database'
          MonitoringConfiguration:
            LogLevel: INFO

Outputs:
  NotebookName:
    Value: !Ref FlinkStudioNotebook
  RoleArn:
    Value: !GetAtt FlinkStudioRole.Arn
  GlueDatabaseName:
    Value: !Ref GlueDatabase
```

---

## Deploy Command
```
aws cloudformation deploy --template-file "C:\Users\B01653960\Downloads\flink-studio-notebook.yaml" --stack-name flink-studio-stack --capabilities CAPABILITY_NAMED_IAM --region eu-west-1 --role-arn arn:aws:iam::739275465799:role/core-CloudformationStackAdmin
